"""Plan schemas for orchestrating data retrieval and marine calculation steps."""

from enum import Enum
from typing import Any, Dict, List, Optional
from backend.agents.schemas.base import BaseModel, Field


class ToolExecutionTarget(str, Enum):
    """Specifies which subsystem/teammate component executes the step."""
    P4_EXTERNAL_TOOL = "p4_external_tool"          # Handled by P4 (MCP / APIs / weather / SST / Chlorophyll)
    P6_MARINE_ANALYTICS = "p6_marine_analytics"    # Handled by P6 (Risk indices, PFZ clustering, wave models)
    INTERNAL_SYNTHESIS = "internal_synthesis"      # Handled internally by P3 (Assembly / formatting)


class PlanStep(BaseModel):
    """A single discrete step in the agent execution plan."""
    step_id: str = Field(..., description="Unique step identifier, e.g., 'step_1'.")
    title: str = Field(..., description="Human-readable title of the step.")
    description: str = Field(..., description="Details on what this step performs.")
    target: ToolExecutionTarget = Field(..., description="Subsystem target responsible for execution.")
    operation_name: str = Field(
        ...,
        description="Name of the P4 tool or P6 function (e.g., 'fetch_ocean_weather', 'compute_pfz_score')."
    )
    parameters: Dict[str, Any] = Field(
        default_factory=dict,
        description="Parameters to pass to the tool/analytic function."
    )
    depends_on: List[str] = Field(
        default_factory=list,
        description="List of step_ids that must complete before this step can run."
    )
    is_required: bool = Field(
        default=True,
        description="Whether failure of this step aborts the workflow or allows soft fallback."
    )


class ExecutionPlan(BaseModel):
    """Complete execution plan generated by the planning node."""
    plan_id: str = Field(..., description="Unique plan identifier.")
    summary: str = Field(..., description="High level summary of the plan.")
    steps: List[PlanStep] = Field(
        default_factory=list,
        description="Ordered list of steps to execute."
    )
    requires_marine_safety_check: bool = Field(
        default=True,
        description="Enforces mandatory safety index calculation prior to fishing advisories."
    )
    estimated_complexity: str = Field(
        default="standard",
        description="Complexity rating: simple, standard, multi_source."
    )
