"""Prompts package for Marine Intelligence orchestrator."""

from .system_prompts import (
    MARINE_SYSTEM_DIRECTIVE,
    FISHERMAN_PERSONA_PROMPT,
    RESEARCHER_PERSONA_PROMPT,
    MARITIME_OPERATOR_PROMPT,
)
from .intent_prompts import INTENT_CLASSIFICATION_PROMPT
from .extraction_prompts import SPATIO_TEMPORAL_EXTRACTION_PROMPT
from .planning_prompts import PLANNING_PROMPT
from .synthesis_prompts import RESPONSE_SYNTHESIS_PROMPT

__all__ = [
    "MARINE_SYSTEM_DIRECTIVE",
    "FISHERMAN_PERSONA_PROMPT",
    "RESEARCHER_PERSONA_PROMPT",
    "MARITIME_OPERATOR_PROMPT",
    "INTENT_CLASSIFICATION_PROMPT",
    "SPATIO_TEMPORAL_EXTRACTION_PROMPT",
    "PLANNING_PROMPT",
    "RESPONSE_SYNTHESIS_PROMPT",
]
